
name: Build, Test, and Deploy to Render


on:
  push:
    branches: ["main"]


env:
  IMAGE_NAME: rollin_up_server


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew
        run: chmod +x ./gradlew

      - name: Run unit test
        run: ./gradlew test

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/production.Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}

